[/Script/Engine.InputSettings]
bAltEnterTogglesFullscreen=True
bUseMouseForTouch=False
bEnableMouseSmoothing=True
bViewAccelerationEnabled=False
DefaultViewportMouseCaptureMode=CapturePermanently_IncludingInitialMouseDown
DefaultViewportMouseLockMode=LockOnCapture
DefaultViewportMouseCaptureModeOnLossOfFocus=NoCapture

; --- 烬域操作映射 ---
+ActionMappings=(ActionName="Select",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=LeftMouseButton)
+ActionMappings=(ActionName="ContextMenu",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=RightMouseButton)
+ActionMappings=(ActionName="EndTurn",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=Enter)
+ActionMappings=(ActionName="ToggleOverlay",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=Tab)
+ActionMappings=(ActionName="BuyCard",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=C)
+ActionMappings=(ActionName="TrainUnit",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=T)
+ActionMappings=(ActionName="DeclareWar",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=W)

+AxisMappings=(AxisName="CameraMoveForward",Scale=1.000000,Key=W)
+AxisMappings=(AxisName="CameraMoveForward",Scale=-1.000000,Key=S)
+AxisMappings=(AxisName="CameraMoveRight",Scale=1.000000,Key=D)
+AxisMappings=(AxisName="CameraMoveRight",Scale=-1.000000,Key=A)
+AxisMappings=(AxisName="CameraZoom",Scale=1.000000,Key=MouseWheelAxis)
+AxisMappings=(AxisName="CameraRotate",Scale=1.000000,Key=MiddleMouseButton)
